## github-actions will create the .env
services:
    db:
        networks:
            - force-network
        image: postgres:16 # postgres:16-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-force}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB:-force_db}
        volumes:
            - db_data:/var/lib/postgresql/data # postgres data volume 
        ports:
            - "5432:5432" # postgres port
        healthcheck:
            # postgres healthcheck
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]   
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 30s

    web:
        networks:
            - force-network
        build:
            context: . # context is the root directory of the project
            dockerfile: Dockerfile
        command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 force.wsgi:application"
        volumes:
            - ./staticfiles:/app/staticfiles
            - ./media:/app/media
            - ./logs:/app/logs
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            DATABASE_URL: ${DATABASE_URL}
            LOCALHOST: ${LOCALHOST}
        healthcheck:
            test: ["CMD", "python", "-c", "import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 8000))"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        depends_on: # before web service starts, db service must be healthy
            db: # db service
                condition: service_healthy # check if db service is healthy

    cloudflared:
        image: cloudflare/cloudflared:latest
        command: tunnel --no-autoupdate run
        environment:
            TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
        networks:
            - force-network
        depends_on:
            web:
                condition: service_healthy
        restart: unless-stopped


networks:
    force-network:
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: 1500
volumes: # volumes are used to persist data across container restarts
    db_data: # db data volume : /var/lib/postgresql/data