# Generated by Django 5.2.9 on 2026-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_trial_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Developer accounts bypass rate limiting'),
        ),
    ]
