# Generated by Django 5.2.9 on 2026-02-09 14:39

from django.db import migrations


def set_developer_role(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    CustomUser.objects.filter(email='irfanemreutkan@outlook.com').update(is_developer=True)


def unset_developer_role(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    CustomUser.objects.filter(email='irfanemreutkan@outlook.com').update(is_developer=False)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_add_is_developer'),
    ]

    operations = [
        migrations.RunPython(set_developer_role, unset_developer_role),
    ]
