"""
Workout views - imports from organized modules for backward compatibility.
All views are now organized in workout/views_modules/ for better maintainability.
"""

# Import all views from organized modules
from .views_modules import (  # CRUD operations; Exercise management; History & Calendar; Templates; Timer; Recovery; Analytics; Programs; Personal Records
    ActivateWorkoutProgramView, ActiveWorkoutCoachView,
    AddExerciseSetToWorkoutExerciseView, AddExerciseToWorkoutView,
    CalendarStatsView, CalendarView, CheckPreviousWorkoutPerformedView,
    CheckWorkoutPerformedTodayView, CoachReviewView, CompleteWorkoutView,
    CreateTemplateWorkoutView, CreateWorkoutProgramView, CreateWorkoutView,
    CurrentProgramDayView, DeactivateWorkoutProgramView, DeleteExerciseSetView,
    DeleteTemplateWorkoutView, DeleteWorkoutExerciseView,
    DeleteWorkoutProgramView, DeleteWorkoutView, ExerciseOptimizationCheckView,
    ExercisePersonalRecordView, GetActiveWorkoutView, GetAvailableYearsView,
    GetExercise1RMHistoryView, GetExerciseLastWorkoutView,
    GetExerciseSetHistoryView, GetMuscleRecoveryStatusView,
    GetRecoveryRecommendationsView, GetRelevantResearchView,
    GetRestPeriodRecommendationsView, GetRestTimerStateView,
    GetTemplateWorkoutsView, GetTrainingFrequencyRecommendationsView,
    GetWorkoutProgramsView, GetWorkoutProgramView, GetWorkoutView,
    NextWorkoutCoachView, OverloadTrendView, PersonalRecordsListView,
    ResumeRestTimerView, StartTemplateWorkoutView, StartWorkoutFromProgramView,
    StopRestTimerView, SuggestNextExerciseView, TotalWorkoutsPerformedView,
    UpdateExerciseOrderView, UpdateExerciseSetView, UpdateWorkoutProgramView,
    UpdateWorkoutView, UserStatsView, VolumeAnalysisView, WorkoutPagination,
    WorkoutSummaryView)

# Re-export everything for backward compatibility
__all__ = [
    'CreateWorkoutView',
    'GetWorkoutView',
    'GetActiveWorkoutView',
    'UpdateWorkoutView',
    'DeleteWorkoutView',
    'CompleteWorkoutView',
    'CheckPreviousWorkoutPerformedView',
    'CheckWorkoutPerformedTodayView',
    'TotalWorkoutsPerformedView',
    'WorkoutPagination',
    'AddExerciseToWorkoutView',
    'AddExerciseSetToWorkoutExerciseView',
    'UpdateExerciseSetView',
    'DeleteExerciseSetView',
    'DeleteWorkoutExerciseView',
    'UpdateExerciseOrderView',
    'GetExercise1RMHistoryView',
    'GetExerciseSetHistoryView',
    'GetExerciseLastWorkoutView',
    'CalendarView',
    'GetAvailableYearsView',
    'CalendarStatsView',
    'CreateTemplateWorkoutView',
    'GetTemplateWorkoutsView',
    'DeleteTemplateWorkoutView',
    'StartTemplateWorkoutView',
    'GetRestTimerStateView',
    'StopRestTimerView',
    'ResumeRestTimerView',
    'GetRecoveryRecommendationsView',
    'GetRestPeriodRecommendationsView',
    'GetTrainingFrequencyRecommendationsView',
    'GetRelevantResearchView',
    'GetMuscleRecoveryStatusView',
    'SuggestNextExerciseView',
    'ExerciseOptimizationCheckView',
    'VolumeAnalysisView',
    'WorkoutSummaryView',
    'UserStatsView',
    'OverloadTrendView',
    'CoachReviewView',
    'NextWorkoutCoachView',
    'ActiveWorkoutCoachView',
    'CreateWorkoutProgramView',
    'GetWorkoutProgramsView',
    'GetWorkoutProgramView',
    'UpdateWorkoutProgramView',
    'DeleteWorkoutProgramView',
    'ActivateWorkoutProgramView',
    'DeactivateWorkoutProgramView',
    'CurrentProgramDayView',
    'StartWorkoutFromProgramView',
    'PersonalRecordsListView',
    'ExercisePersonalRecordView',
]
