"""
Workout views - imports from organized modules for backward compatibility.
All views are now organized in workout/views_modules/ for better maintainability.
"""

# Import all views from organized modules
from .views_modules import (
    # CRUD operations
    CreateWorkoutView,
    GetWorkoutView,
    GetActiveWorkoutView,
    UpdateWorkoutView,
    DeleteWorkoutView,
    CompleteWorkoutView,
    CheckPreviousWorkoutPerformedView,
    CheckWorkoutPerformedTodayView,
    TotalWorkoutsPerformedView,
    WorkoutPagination,
    # Exercise management
    AddExerciseToWorkoutView,
    AddExerciseSetToWorkoutExerciseView,
    UpdateExerciseSetView,
    DeleteExerciseSetView,
    DeleteWorkoutExerciseView,
    UpdateExerciseOrderView,
    # History & Calendar
    GetExercise1RMHistoryView,
    GetExerciseSetHistoryView,
    GetExerciseLastWorkoutView,
    CalendarView,
    GetAvailableYearsView,
    CalendarStatsView,
    # Templates
    CreateTemplateWorkoutView,
    GetTemplateWorkoutsView,
    DeleteTemplateWorkoutView,
    StartTemplateWorkoutView,
    # Timer
    GetRestTimerStateView,
    StopRestTimerView,
    ResumeRestTimerView,
    # Recovery
    GetRecoveryRecommendationsView,
    GetRestPeriodRecommendationsView,
    GetTrainingFrequencyRecommendationsView,
    GetRelevantResearchView,
    GetMuscleRecoveryStatusView,
    SuggestNextExerciseView,
    ExerciseOptimizationCheckView,
    # Analytics
    VolumeAnalysisView,
    WorkoutSummaryView,
    UserStatsView,
    OverloadTrendView,
    # Programs
    CreateWorkoutProgramView,
    GetWorkoutProgramsView,
    GetWorkoutProgramView,
    UpdateWorkoutProgramView,
    DeleteWorkoutProgramView,
    ActivateWorkoutProgramView,
    DeactivateWorkoutProgramView,
    CurrentProgramDayView,
    # Personal Records
    PersonalRecordsListView,
    ExercisePersonalRecordView,
)

# Re-export everything for backward compatibility
__all__ = [
    'CreateWorkoutView',
    'GetWorkoutView',
    'GetActiveWorkoutView',
    'UpdateWorkoutView',
    'DeleteWorkoutView',
    'CompleteWorkoutView',
    'CheckPreviousWorkoutPerformedView',
    'CheckWorkoutPerformedTodayView',
    'TotalWorkoutsPerformedView',
    'WorkoutPagination',
    'AddExerciseToWorkoutView',
    'AddExerciseSetToWorkoutExerciseView',
    'UpdateExerciseSetView',
    'DeleteExerciseSetView',
    'DeleteWorkoutExerciseView',
    'UpdateExerciseOrderView',
    'GetExercise1RMHistoryView',
    'GetExerciseSetHistoryView',
    'GetExerciseLastWorkoutView',
    'CalendarView',
    'GetAvailableYearsView',
    'CalendarStatsView',
    'CreateTemplateWorkoutView',
    'GetTemplateWorkoutsView',
    'DeleteTemplateWorkoutView',
    'StartTemplateWorkoutView',
    'GetRestTimerStateView',
    'StopRestTimerView',
    'ResumeRestTimerView',
    'GetRecoveryRecommendationsView',
    'GetRestPeriodRecommendationsView',
    'GetTrainingFrequencyRecommendationsView',
    'GetRelevantResearchView',
    'GetMuscleRecoveryStatusView',
    'SuggestNextExerciseView',
    'ExerciseOptimizationCheckView',
    'VolumeAnalysisView',
    'WorkoutSummaryView',
    'UserStatsView',
    'OverloadTrendView',
    'CreateWorkoutProgramView',
    'GetWorkoutProgramsView',
    'GetWorkoutProgramView',
    'UpdateWorkoutProgramView',
    'DeleteWorkoutProgramView',
    'ActivateWorkoutProgramView',
    'DeactivateWorkoutProgramView',
    'CurrentProgramDayView',
    'PersonalRecordsListView',
    'ExercisePersonalRecordView',
]
